### ISSUE TITLE
Add Appveyor

### ISSUE THREAD

**Issue by Minoru** [Minoru/git-submerge#14]
- [x] Set up a build
- [x] Add a badge to README

**Comment by Minoru** [comment]
Can't get it to work. @ForNeVeR was successful in building git-submerge locally (after updating Rust and adding CMake to the PATH), so not everything is lost yet. ForNeVeR also said he'd look into AppVeyor to see if anything can be done. I'll occupy myself with something else for now.

**Comment by ForNeVeR** [comment]
I [was able](https://ci.appveyor.com/project/ForNeVeR/git-submerge/build/1.0.4) to produce the build using x86_64-pc-windows-msvc toolchain on Appveyor. Should I send the PR with only that toolchain enabled?

The problem with others toolchains is probably something with rustup, and its' command line options are complicated enough.

It's not easy for me to test on other toolchains, because I'm using only x86_64-pc-windows-msvc on Windows myself.

**Comment by ForNeVeR** [comment]
Okay, the current plan I propose:

1. Drop all toolchains except x86_64-pc-windows-msvc: we'll start to test other toolchains only if there'll be problems with them; _probably not_.
2. Publish build artifacts from Appveyor so @Minoru could publish them at the releases page.
3. I should check the program myself. I'm sure it builds and executes with `cargo run`, but I haven't yet verified the results on Windows.

**Comment by Minoru** [comment]
Doing just x86_64 releases make me a bit uncomfortable, but according to [Steam Hardware survey](http://store.steampowered.com/hwsurvey/) for May 2017 92.95% of Windows users run 64bit, so it's probably no big deal.

Don't know how to link to the dated survey, so here's a copy of relevant data:

Version | Market share
----------|-------------
Windows 10 64 bit   | 51.06%
Windows 7 64 bit    | 33.58%
Windows 8.1 64 bit  | 7.40%
Windows 7   | 4.67%
Windows 10  | 1.00%
Windows XP 32 bit   | 0.92%
Windows 8 64 bit    | 0.91%
Windows 8.1 | 0.21%
Windows Vista 32 bit    | 0.09%
Windows 8   | 0.08%

**Comment by ForNeVeR** [comment]
On the other hand, I believe that the somewhat standard practice today is to produce *both* x32 and x64 builds (to offer them from [Choco](https://chocolatey.org/), for example). If we're going to comply the modern Windows software distribution standards (and that's a good thing), I think we should do both.

I'll address that in my PR.

**Comment by ForNeVeR** [comment]
I have verified that git-submerge works on Windows.
