### ISSUE TITLE
Figure out what to do with .gitignore in submodule's dir

### ISSUE THREAD

**Issue by Minoru** [Minoru/git-submerge#5]
- [x] Check if Git deals fine with multiple `.gitignore` files, or if it wants to pull them all to the root of the repo.
- [x] Decide if we need to do anything on this and file separate issues with actionable items.

**Comment by ForNeVeR** [comment]
Git deals fine with multiple `.gitignore` files, I don't think we want to do anything about it.

**Comment by Minoru** [comment]
Yeah, you're totally right. gitignore(5) explains how multiple files are processed right in the DESCRIPTION section. Gonna clone this issue, then. Thanks!
